imaginary-dev/imaginary-dev

transformers/babel/src/babelTypeToJsonSchema.test.ts, util/jest.config.ts, util/package.json, util/src/schema.test.ts, util/src/schema.ts, util/src/ts-doc.test.ts
- add jest
- schema tests
- tests for tsdoc parser
- test for babelTypetoJsonSchema
=> Tests for util, babel

example-clients/nextjs-playground/package.json, example-clients/nextjs-playground/src/components/ParamEditor.tsx, example-clients/nextjs-playground/src/components/SampleEditor.tsx, example-clients/nextjs-playground/src/components/ScenarioCodeEditor.tsx, example-clients/nextjs-playground/src/state/scenarios.ts, example-clients/nextjs-playground/src/util/presetScenarios.ts, package-lock.json, package.json, prompt-engine/package.json, transformers/babel/package.json, transformers/babel/src/babelTypeToJsonSchema.ts, transformers/typescript/package.json
- add padding to badge
- better error message
- add 2 movie scenarios
- add more demos, fix formatting
- support enter in textarea
- ruder message
- set version to * to allow internal linking
- fix inter-package references
=> Add more examples that (mostly) work

package-lock.json, package.json
- try pulling nrwl for linux back out?
- fix package-lock by upgrading nx
=> Fix mac build 🙄

nextjs-util/jest.config.ts, nextjs-util/package.json, nextjs-util/setupJest.ts, nextjs-util/src/browser.test.ts, nextjs-util/src/browser.ts, nextjs-util/src/server.test.ts, nextjs-util/src/server.ts, package-lock.json, prompt-engine/util.ts
- add clean
- fix return type
- add docs
- add test for browser
- better tests, errors
=> More/better tests for nextjs API stuff, so we can build on it

example-clients/nextjs-playground/src/components/ScenarioCodeEditor.tsx, example-clients/nextjs-playground/src/util/presetScenarios.ts
- add placeholder as the first entry in the preset
- when we get focus, bring in placeholder as real content
=> Playground starting improvements

package-lock.json, vsc-extension/package.json, vsc-extension/src-shared/source-info.ts, vsc-extension/src-views/function-panel/App.tsx, vsc-extension/src/extension.ts, vsc-extension/src/function-tree-provider.ts, vsc-extension/src/source-info.ts, vsc-extension/src/source-utils.ts, vsc-extension/tsconfig.json, vsc-extension/tsconfig.react.json
This sends the current source list to the webview, to be rendered by react... screenshot shows source list in webview:
- add recoil-sync
- start to wire up message passing
- add webpack cli
- make a shared dir, move shared interfaces there
- dispatch message to web view with current sources list
=> Basic dispatching of messages to react

transformers/shared-tests/src/basic-parsing-tests.ts, transformers/typescript/src/ts-prompt-transformer.ts
=> Fix for error on generic functions, and better error reporting

vsc-extension/src-views/function-panel/App.tsx, vsc-extension/src-views/shared/ExtensionState.tsx, vsc-extension/src/extension.ts, vsc-extension/src/imaginary-message-router.ts, vsc-extension/src/util/react-webview-provider.ts
- wire up emitting events from webviews
- properly dispose of the router
=> Wire up routing of messages from webview -> extension host

vsc-extension/src/extension.ts, vsc-extension/src/function-tree-provider.ts, vsc-extension/src/util/editor.ts
- fix edge cases around cursor position and currently selected function
- generalized return value
- progress on, but not finished, treeview revealing
=> Fix cursor position when clicking on function

package-lock.json, vsc-extension/src-shared/messages.ts, vsc-extension/src-views/shared/ExtensionState.tsx, vsc-extension/src-views/shared/InputPanel.tsx, vsc-extension/src-views/shared/OutputPanel.tsx, vsc-extension/src-views/shared/state.ts, vsc-extension/src/extension.ts, vsc-extension/src/imaginary-message-router.ts, vsc-extension/src/util/react-webview-provider.ts, vsc-extension/src/util/source.ts, vsc-extension/src/util/state.ts, vsc-extension/src/util/types.ts
- run npm install
- change sources to use the state map
- do state updates relative to providers
- oops, fix testcase bug
- mechanical conversion of selectedFunction to state updates
- remove dead updateSeldctedTestCases, not used yet
- convert test cases over too
- make sure to proactively update state
- get rid of updateSources event
- add stronger typing for state map
- propagate Map -> TypedMap
=> Fully unify shared state between extension and the rest of the app

package-lock.json, package.json
- update ts-jest eslint-config-next @types/vscode @types/react
- update webpack tailwindcss @typescript-eslint/parser @typescript-eslint/eslint-plugin
- upgrade @babel/core @babel/parser @babel/plugin-syntax-typescript @babel/traverse
- upgrade @chakra-ui/icons @next/font next
=> Upgrade packages 2023-04-07

package-lock.json, vsc-extension/__mocks__/vscode.ts, vsc-extension/jest.config.ts, vsc-extension/package.json, vsc-extension/src-shared/serialize-source.test.ts, vsc-extension/src-shared/serialize-source.ts, vsc-extension/src/util/editor.ts, vsc-extension/src/util/serialized-source.test.ts
- add vscode mock
- fix import sor mock works
- add mock decl for vscode
- tests for serialized-soruce
- tests for makeSerialiable
- add coverage command
=> Add some tests for utility functions

transformers/typescript/src/index.ts, transformers/typescript/src/ts-node-to-json-schema.ts, vsc-extension/src-views/components/InputPanel.tsx, vsc-extension/src-views/components/OutputPanel.tsx, vsc-extension/src/rpc-handlers.ts
- add ast-only conversion
- try using new AST
- better comments
- switch to using the new JSONSchema translater
- handle promises in return values
- better formatting
=> Use AST-based schema conversion, format output better

vsc-extension/src-views/components/DebugPanel.tsx, vsc-extension/src-views/components/OutputPanel.tsx, vsc-extension/src-views/components/ParamEditor.tsx, vsc-extension/src-views/components/TestCasesList.tsx, vsc-extension/src/rpc-handlers.ts, vsc-extension/src/util/secrets.ts
- format prev, not current, and use code for beautification
- better debug button
- break up some files
- clear a secret
=> Add clear API key button, minor code cleanup/refactoring, fix "prev" output

vsc-extension/src-views/components/OutputPanel.tsx, vsc-extension/src-views/components/TestCaseEditor.tsx
=> Temporarily removed temperature editor and previous output column.

vsc-extension/src-views/components/OutputPanel.tsx, vsc-extension/src-views/components/TestCasesList.tsx, vsc-extension/src/rpc-handlers.ts
- more examples for better names
- make whitespace clickable
- tweak prompt for better name
- add some sticky positioning for better scrolling
- allow clickable test case when blank
=> Some minor polish - scrolling, clickability, etc

package-lock.json, transformers/typescript/src/ts-node-to-json-schema.ts, vsc-extension/package.json, vsc-extension/src-views/components/OutputPanel.tsx, vsc-extension/src-views/components/TestCaseDashboard.tsx, vsc-extension/src/util/react-webview-provider.ts, vsc-extension/tsconfig.react.json, vsc-extension/types.d.ts, vsc-extension/webpack.config.js
- break out TestCaseDashboard
- add url-loader for loading images
- make pngs loadable in react
- allow images to load via webpack
- update CSP to allow for data: urls
- add strawman for blank selection
- nicer formatting of function decl
- include Array<T>
=> More polish: empty panel, handling Array, formatting declaration

vsc-extension/src-views/components/ParamEditor.tsx, vsc-extension/src-views/components/TestCaseDashboard.tsx, vsc-extension/src/extension.ts, vsc-extension/src/util/editor.ts, vsc-extension/src/util/source.ts
- checkbox for boolean
- move label inside, allowing checkbox to have its own label
- add persistence of test case state
=> Overly simple test case serialization

package-lock.json, vsc-extension/package.json
This will allow us to publish the extension
=> rename package, cannot have @-based package names

vsc-extension/src-views/components/GenerateTestCasesButton.tsx, vsc-extension/src/rpc-handlers.ts
=> Moved to generating single test case. Fixes #92

vsc-extension/src-shared/testcases.ts, vsc-extension/src-views/components/RunButton.tsx, vsc-extension/src-views/components/TestCaseDashboard.tsx, vsc-extension/src-views/components/TestCasesList.tsx
=> Fix for #105. Deletes output along with test cases.

vsc-extension/package.json, vsc-extension/src/extension.ts
=> add command to clear API key

vsc-extension/src-shared/source-info.ts, vsc-extension/src-views/components/ExtensionState.tsx, vsc-extension/src-views/components/RunButton.tsx, vsc-extension/src-views/components/TestCaseDashboard.tsx, vsc-extension/src-views/components/TestCasesList.tsx, vsc-extension/src/rpc-handlers.ts, vsc-extension/src/util/react-webview-provider.ts
- better warnings for failures
- capture the latest error so we dont keep auto-running broken examples
- add loading state in the button
=> better error handling so we do not keep running broken tests

vsc-extension/src-views/components/RunButton.tsx
Reverts imaginary-dev/imaginary-dev#117
=> Revert "Fix #110. Auto-run tests."

vsc-extension/__mocks__/vscode.ts, vsc-extension/src/util/editor.test.ts, vsc-extension/src/util/editor.ts, vsc-extension/src/util/persistence.test.ts, vsc-extension/src/util/source.test.ts
=> Some tests for editor, persistence

vsc-extension/__mocks__/vscode.ts, vsc-extension/src/extension.ts, vsc-extension/src/util/diagnostics.test.ts, vsc-extension/src/util/diagnostics.ts
- add inline diagnostics to help find errors in return values
- slightly more diagnostics
=> Add inline diagnostics for imaginary function problems

package-lock.json, vsc-extension/package.json, vsc-extension/src-shared/testcases.test.ts, vsc-extension/src-shared/testcases.ts, vsc-extension/src-views/components/Drawer.tsx, vsc-extension/src-views/components/GenerateTestCasesButton.tsx, vsc-extension/src-views/components/NewTestDrawer.tsx, vsc-extension/src-views/components/ParamEditor.tsx, vsc-extension/src-views/components/RecoilSyncWebview.tsx, vsc-extension/src-views/components/RunButton.tsx, vsc-extension/src-views/components/TestCaseInputEditor.tsx, vsc-extension/src-views/function-panel/App.tsx, vsc-extension/src-views/input-panel/App.tsx, vsc-extension/src/imaginary-message-router.ts, vsc-extension/src/util/diagnostics.ts, vsc-extension/src/util/persistence.ts, vsc-extension/src/util/types.ts
- move new tests to the front of the test list
- add swr for better caching/etc
- fix return type from rpc signature
- switch over to useSWR to avoid double-requests
- autofocus first field
- add SWR cache
- fix error in bootstrapping
- fix async signature for readability
=> focus on new test, modal overlay, fix edge cases when bootstrapping

vsc-extension/src-views/components/OutputPanel.tsx, vsc-extension/src-views/components/TestCaseDashboard.tsx, vsc-extension/src-views/components/TestCasesList.tsx, vsc-extension/src-views/function-panel/App.tsx, vsc-extension/src-views/input-panel/App.tsx, vsc-extension/src/extension.ts, vsc-extension/src/util/react-webview-provider.ts
- make sure to initialize extension local state
- remove SWRConfig for now, seems to cause initialization problems
- tweak scrolling behavior a bit
=> Fix some scrolling behavior, errors when first loading

vsc-extension/src-views/components/GenerateTestCasesButton.tsx, vsc-extension/src/has-access-enum.ts, vsc-extension/src/rpc-handlers.ts
=> Fix for Plugin: if you install and click "Generate Test Case" you get a error  #135

vsc-extension/src-views/components/GenerateTestCasesButton.tsx
=> Fix for Plugin: Generate Test Case gets outputs and test cases out of sync #137

vsc-extension/README.md, vsc-extension/src-views/components/Drawer.tsx, vsc-extension/src-views/components/GenerateTestCasesButton.tsx, vsc-extension/src-views/components/OutputPanel.tsx, vsc-extension/src-views/components/ParamEditor.tsx, vsc-extension/src-views/components/TestCaseDashboard.tsx, vsc-extension/src-views/components/TestCaseInputEditor.tsx, vsc-extension/src-views/components/TestCasesList.tsx
(hopefully) fixes #140 
- dynamically growing text fields when editing
- lint
- move buttons to the top, fix stretch/alignment
- clean up fonts/etc
- clean up grid and flex layout to allow for flexible regions
=> UI Polish: fonts, selection, scrolling

example-clients/nextjs-api/package.json, example-clients/nextjs-playground/package.json, package-lock.json, package.json, transformers/typescript/package.json, vsc-extension/package-lock.json
- run npm install
- update -ws tailwindcss next @types/react-dom @types/react
- update -ws @chakra-ui/react @next/font
- update nx
- update @types/node
=> Package update

vsc-extension/src/util/editor.test.ts, vsc-extension/src/util/editor.ts
- better handle relative paths when there is not workspace
- add some tests
=> Attempt to handle lack of workspaceFolders

prompt-engine/src/imaginary-runtime.test.ts, prompt-engine/src/imaginary-runtime.ts, vsc-extension/src-views/components/TestCaseDashboard.tsx
- make sure to throw parsing errors too
- put error in red, no wrap
=> If response is an error, put the error in the output panel

vsc-extension/src-shared/testcases.ts, vsc-extension/src-views/components/GenerateTestCasesButton.tsx, vsc-extension/src-views/components/NewTestDrawer.tsx
=> Fix for Plugin: Add new test case causes off by one with outputs #153

vsc-extension/package.json, vsc-extension/src/extension.ts, vsc-extension/src/util/editor.ts
- comment out the lefthand panel for now
- allow tree navigation to work with no workspace
=> Remove inputs panel, fix selection in tree

vsc-extension/src-views/components/TestCaseDashboard.tsx, vsc-extension/src/rpc-handlers.ts, vsc-extension/src/util/comments.test.ts, vsc-extension/src/util/comments.ts, vsc-extension/src/util/editor.ts
- plumb through command to add output, emitting to console
- almost working using WorkspaceEdit
- more progress but not working
- working, with minor crash
- fix edge cases
=> Add subtle "add example" button

.github/workflows/ci.yaml, .npmrc, package-lock.json, package.json, vsc-extension/package-lock.json, vsc-extension/package.json, vsc-extension/src/util/editor.test.ts
- add back running tests in the extension
- fix test
=> Add back vsc tests
